apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    releaseName: alloy
    namespace: monitoring
    valuesFile: alloy.values.yaml